name: Sync Upstream

on:
  schedule:
    - cron: '0 0 * * *' # 每天 00:00 UTC 运行
  workflow_dispatch:  # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: 检出你的 Fork 仓库
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: 配置 Git 用户信息
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: 配置 GitHub 身份验证
        run: |
          git config --global credential.helper 'store'
          echo "https://github-actions[bot]:${{ secrets.GITHUB_TOKEN }}@github.com" > ~/.git-credentials

      - name: 添加上游仓库
        run: |
	    git remote add upstream https://github.com/Guovin/iptv-api.git
	    git fetch upstream
	    git checkout master
	    git merge upstream/master --allow-unrelated-histories --strategy-option theirs -X theirs

      - name: 排除工作流文件
        run: |
	    git reset HEAD .github/workflows/  # 确保 .github/workflows/ 不被加入暂存区
	    git restore --staged .github/workflows/  # 取消暂存
	    git checkout .github/workflows/  # 恢复 .github/workflows/ 为原始状态
	    git add .  # 添加其他文件
	    git commit --allow-empty -m "同步上游代码，并忽略工作流文件"

      - name: 推送到 Fork 仓库
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin master --force # 这里改为你的上游主要分支，一般可能是main或者master