name: Sync Upstream

on:
  schedule:
    - cron: '0 0 * * *' # 每天 00:00 UTC 运行
  workflow_dispatch:  # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: 检出你的 Fork 仓库
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: 配置 Git 用户信息
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: 添加上游仓库
        run: |
          git remote add upstream https://github.com/Guovin/iptv-api.git
          git fetch upstream

      - name: 重置并恢复 `.github/workflows/` 文件
        run: |
          git restore --source=HEAD --staged .github/workflows/
          git restore --source=HEAD .github/workflows/
          git reset HEAD .github/workflows/
          git checkout .github/workflows/

      - name: 排除 `.github/workflows/` 目录的变更
        run: |
          find .github/workflows -type f | xargs git update-index --skip-worktree

      - name: 合并上游代码
        run: |
          git checkout master
          git merge upstream/master --allow-unrelated-histories -X theirs

      - name: 再次排除 `.github/workflows/`
        run: |
          find .github/workflows -type f | xargs git update-index --skip-worktree

      - name: 推送到 Fork 仓库
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin master --force
